### ISSUE TITLE
Implement as Nodelet and use image_proc

### ISSUE THREAD

**Issue by FranekStark** [basler/pylon-ros-camera#10]
Hi,
why don't you implement the node as "Nodelet"  and then use the rectifier from the [image_pipeline](http://wiki.ros.org/image_proc?distro=melodic) to improve it?
I think this is the standard way and would give the software more modularity.

**Comment by pablo-quilez** [comment]
Hi,

because this will require a big refactoring of the driver. Indeed is a good idea. You are welcome to contribute!

**Comment by FranekStark** [comment]
Ok. 
I was afraid of something like this. ;)
