### ISSUE TITLE
error: ‘pylon_camera::PylonCameraImpl<pylon_camera::USBCameraTrait>::CBaslerInstantCameraT {aka class Pylon::CBaslerUniversalInstantCamera}’ has no member named ‘BslLightSourcePreset’; did you mean ‘LightSourcePreset’?

### ISSUE THREAD

**Issue by knightdby** [basler/pylon-ros-camera#109]
Camera: acA1920-40gc
Platform: jetson xavier, ARM64
Pylon: 5.2.0

`src/pylon_camera/include/pylon_camera/internal/impl/pylon_camera_base.hpp:2503:83: error: ‘Basler_UniversalCameraParams::BslLightSourcePresetEnums’ has not been declared
                 cam_->BslLightSourcePreset.SetValue(Basler_UniversalCameraParams::BslLightSourcePresetEnums::BslLightSourcePreset_Off);`

**Comment by m-binev** [comment]
@knightdby Hi, I recommend using the master branch, which includes pylon 6.2. Cheers

**Comment by knightdby** [comment]
when i use pylon 6.2, then error:
![image](https://user-images.githubusercontent.com/75298418/169514168-60b0f15e-4bff-42c3-b917-6171083cb6e6.png)

**Comment by m-binev** [comment]
@knightdby can you check the latest Readme: https://github.com/basler/pylon-ros-camera/tree/galactic 
Especially:
GigE Devices
No connection with connected camera
To be sure to be able to connect to a specific camera, its network configuration must be manually set through Basler's pylon IP configurator. To do so, click on the camera in the list of connected devices, select the Static IP option, set an IP Address within the same range as the one of your computer, and set the same Subnet Mask as the one from your computer.

and:
Setting device user id

**Comment by FrancoisPicardDTI** [comment]
@knightdby can you post the whole from the moment you launch the node please?

**Comment by knightdby** [comment]
@m-binev thanks for your reply,I haven't set the use ID before. Wait for me to try,thanks.

**Comment by knightdby** [comment]
@FrancoisPicardDTI Thank you for your reply,The whole terminal log is as follows：
![image](https://user-images.githubusercontent.com/75298418/169622842-5c027311-29ca-4019-a8ed-6a941b1bbd92.png)

**Comment by FrancoisPicardDTI** [comment]
Hello @knightdby 
Thank you for the logs,
As it is specified in the logs, the camera model you're using, alA1920-40gc, is a limited low-cost camera and is not compatible with the current implementation of the ROS driver. Due to missing camera features, the current implementation does not recognize the camera model, preventing thus using this camera. We recommend using regular Basler cameras instead.

**Comment by knightdby** [comment]
@m-binev 
Thank you for your suggestion. I now use ROS image transport compression for data transmission, which can solve the problem of insufficient bandwidth, but it can not be completely solved.
Then, I would like to ask you that the exposure time cannot be set in the ROS driver:
![image](https://user-images.githubusercontent.com/75298418/172118937-58cec902-e583-4fa2-968b-cc8ee913285f.png)
Camera: acA1920-40gc
Platform: jetson xavier, ARM64
Pylon: 5.2.0 and 5.1.0
Looking forward to your reply,Best wishes to you!

**Comment by m-binev** [comment]
@knightdby Hi, I'm glad I could help. As per the exposure time: why don't you use the latest implementation based on pylon 6.2/6.3? This should make lots of things easier. Otherwise, I don't see what's the exact parameter call you make, but this camera should support the parameter ExposureTimeAbs, which controls the exposure time. Of course, this one is not writable while ExposureAuto is set, i.e., make sure you are not running the auto exposure. Cheers

**Comment by knightdby** [comment]
@m-binev 
Thank you for your reply. More information is as follows:
![image](https://user-images.githubusercontent.com/75298418/172751069-34f9fb04-e9e1-4d7e-9f10-e13c6b2605cc.png)
![image](https://user-images.githubusercontent.com/75298418/172751199-314311ec-b5ac-42e5-b724-04ee09c6b3dd.png)
![image](https://user-images.githubusercontent.com/75298418/172751229-32dcf979-0260-4734-84c3-aee465c36908.png)
Neither exposure time nor brightness can be written to the camera.

**Comment by m-binev** [comment]
@knightdby Hi, I don't have hardware to test that, but looking at the raw code, a call to setting the brightness (this is no camera parameter), will try to set AutoExposure and AutoGain. That is, after that you won't be able to write to exposure time or gain. Also, I still recommend you using the latest driver version instead)). To troubleshoot things, please power off the camera and try to disable the brightness and any automatic settings. Cheers

**Comment by knightdby** [comment]
@m-binev Thanks for your help, everything is all right
