### ISSUE TITLE
Problem with catkin_make 

### ISSUE THREAD

**Issue by antun008** [basler/pylon-ros-camera#113]
Hello,
when I execute catkin_make,  I get this error:
![image](https://user-images.githubusercontent.com/49721808/172047421-044b59b0-04f5-45ab-826c-d6a490123c8f.png)
[100%] Linking CXX executable /home/antek/programi/catkin_ws_pylon/devel/lib/pylon_camera/pylon_camera_node
/home/antek/programi/catkin_ws_pylon/devel/lib/libpylon_camera.so: undefined reference to `cv::Mat::Mat()'
collect2: error: ld returned 1 exit status
pylon-ros-camera/pylon_camera/CMakeFiles/pylon_camera_node.dir/build.make:170: recipe for target '/home/antek/programi/catkin_ws_pylon/devel/lib/pylon_camera/pylon_camera_node' failed
make[2]: *** [/home/antek/programi/catkin_ws_pylon/devel/lib/pylon_camera/pylon_camera_node] Error 1
CMakeFiles/Makefile2:4390: recipe for target 'pylon-ros-camera/pylon_camera/CMakeFiles/pylon_camera_node.dir/all' failed
make[1]: *** [pylon-ros-camera/pylon_camera/CMakeFiles/pylon_camera_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j6 -l6" failed

Can someone help me plssssss

**Comment by nickzherdev** [comment]
It looks like you don't have OpenCV installed
`sudo apt-get install libopencv-dev`

**Comment by FrancoisPicardDTI** [comment]
@antun008 hello,
It looks like you're are using OpenCV somewhere. The pylon driver does not use it originally so I think your error is related to your own application. Try indeed to install OpenCV to see if it solves your problem.

**Comment by FrancoisPicardDTI** [comment]
Hello @antun008  
So, just for confirmation, pylon itself has never included OpenCV. This issue may be due to the fact you are using drag&bot, or the version of the pylon driver bound to it. Is that the case?
The "libpylon_camera.so" library is not a native pylon library, thus, it must be coming from drag&bot.
