### ISSUE TITLE
Harware syncronazation of Two Basler Cameras - ROS

### ISSUE THREAD

**Issue by farhad-dalirani** [basler/pylon-ros-camera#114]
Hello,

I have two Basler cameras that are connected to my PC by USB cables. I ordered another cable that connects two cameras to each other.
 
I want to synchronize these to cameras in which, both of them get images at the same time. 

I use Ubuntu-18.04 and ROS Melodic.

Best,

**Comment by FrancoisPicardDTI** [comment]
Hello @farhad-dalirani 
Closing this issue as it seems that it is closely related to #125.
