### ISSUE TITLE
Running two Basler cameras simultaneously

### ISSUE THREAD

**Issue by farhad-dalirani** [basler/pylon-ros-camera#119]
Hello everyone,

I have two Basler cameras that I want to run simultaneously. I was able to run them with `<group>` tag in the launch file, which resulted in two different topics `left_basler/pylon_camera_node` and `right_basler/pylon_camera_node`.

However, I want to have these two cameras with the name `/pylon_camera_node/left_basler` and '`/pylon_camera_node/right_basler`.

I don't know how to achieve that. If you have any suggestions, please let me know.

Best,

**Comment by FrancoisPicardDTI** [comment]
Hello @farhad-dalirani 
I am closing this one as I guess it is linked to issue #125.
