### ISSUE TITLE
Unable to receive data on more than 5 USB cameras

### ISSUE THREAD

**Issue by bouletjeanalexis** [basler/pylon-ros-camera#12]
Hi, I got a vision system using 6 basler camera acA1920-40uc.
I am able to launch and record 5 of them a without issue.
When I connect the sixth one i receive no data on that topic
All cam have a unique device_user_id from cam0 to cam5

Here is the message i got when connecting the last one

> [ERROR] [1570648293.510069443]: Couldn't find the camera that matches the given DeviceUserID: cam5! Either the ID is wrong or the cam is not yet connected
[ERROR] [1570648295.510965631]: Couldn't find the camera that matches the given DeviceUserID: cam5! Either the ID is wrong or the cam is not yet connected
[ INFO] [1570648297.509387785]: Found the desired camera with DeviceUserID cam5: acA1920-40uc
[ WARN] [1570648297.622168215]: No camera present. Keep waiting ...
[ WARN] [1570648299.265209747]: No User Set Is selected, Camera current setting will be used
[ INFO] [1570648299.267531490]: Cam supports the following [GenAPI|ROS] image encodings: ['Mono8'|'mono8'] ['BayerRG8'|'bayer_rggb8'] ['BayerRG12'|'bayer_rggb16'] ['BayerRG12p'|'NO_ROS_EQUIVALENT'] ['RGB8'|'rgb8'] ['BGR8'|'bgr8'] ['YCbCr422_8'|'NO_ROS_EQUIVALENT'] 
[ INFO] [1570648299.355252985]: camera calibration URL: file:///home/sixmetrix/catkin_ws/src/pylon-ros-camera/pylon_camera/config/cam5_calib.yaml
[ WARN] [1570648299.362856675]: [cam5] does not match name narrow_stereo in file /home/sixmetrix/catkin_ws/src/pylon-ros-camera/pylon_camera/config/cam5_calib.yaml
[ INFO] [1570648299.377006538]: Setting gamma to 1, reached: 1
[ INFO] [1570648300.996723716]: Setting brightness to: 100, reached: 99
[ INFO] [1570648301.002561299]: Startup settings: encoding = 'bayer_rggb8', binning = [1, 1], exposure = 22285, gain = 0, gamma = 1, shutter mode = global
[ INFO] [1570648301.002960076]: Start image grabbing if node connects to topic with a frame_rate of: 5 Hz
[ INFO] [1570648301.003087051]: Camera is calibrated
[ WARN] [1570648301.003396208]: diagnostic_updater: No HW_ID was set. This is probably a bug. Please report it. For devices that do not have a HW_ID, set this value to 'none'. This warning only occurs once all diagnostics are OK so it is okay to wait until the device is open before calling setHardwareID.

Any idea how to solve the issue?

**Comment by pablo-quilez** [comment]
Hello,

After checking the driver we didn't found a reason why this is happening. Could you please provide more information:
- Are you trying to use all the cameras at the same time?
- Is always the same camera giving trouble or is independently of the order you connect the cameras? Is always the last camera connected?
- When you connect with pylon viewer to the camera, which value has Device User ID?
- Did you somehow modified the Device User ID?
- Could you try just to connect the affected camera and leave device_user_id: "" empty in the config.yaml of the driver?

Thanks!
Pablo
