### ISSUE TITLE
Hardware Synchronisation of Two USB 3.0 Basler Cameras

### ISSUE THREAD

**Issue by farhad-dalirani** [basler/pylon-ros-camera#125]
# problem explanation

Hello,

I use two USB 3.0 Basler cameras as a stereo system on a car. Since the car moves, I need to synchronize two cameras. For this reason, I bought a 6-pin cable that connects cameras. 

I want the left camera to be the master and generate a trigger, and I want the right camera to be a slave and start to capture by receiving a trigger.

I did the setting in pylon viewer, which works in pylon viewer. I stored the setting for two cameras in their user set 2. When I want to work with ROS, I load the user set 2 for each camera. However, I get an error. The left camera (master) works at 32 fps (its maximum). However, the right camera (slave) does not work, and this error happens:

```
An image grabbing exception in pylon camera occurred: waiting for frame trigger ready time out.
Error: Grab was not successful
Failed to grab image, can't calculate current brightness

An image grabbing exception in pylon camera occurred: waiting for frame trigger ready time out.
Error: Grab was not successful
.
.
.
```

To give you more detail, in the following, I provided the information:
- the setting for the left camera in pylon viewer, which I save in user set 2
- the setting for the right camera in pylon viewer, which I save in user set 2
- ROS launch file
- ROS config for the left camera
- ROS config for the right camera
- Error message and information related to image topics

## the setting for the left camera in pylon viewer, which I save in user set 2
![left-1](https://user-images.githubusercontent.com/65308831/181365419-444620ba-d147-4dca-b0fa-a659a9be57bb.png)
![left-2](https://user-images.githubusercontent.com/65308831/181365444-48c3fc9e-18f3-4a8c-942f-b56a77c58858.png)
![left-3](https://user-images.githubusercontent.com/65308831/181365462-093d8f33-586f-4eb3-9460-30479a85cb5a.png)
![left-4](https://user-images.githubusercontent.com/65308831/181365473-5de29c93-41aa-49ee-a4ab-55df1bc6fa04.png)
![left-5](https://user-images.githubusercontent.com/65308831/181365488-b3411d11-b881-404b-9535-fd5d8eaf5ec2.png)
![left-6](https://user-images.githubusercontent.com/65308831/181365519-0bb85d33-6f97-46fa-9b7e-25a1a148e32f.png)

## the setting for the right camera in pylon viewer, which I save in user set 2
![right-1](https://user-images.githubusercontent.com/65308831/181365551-51a5fe70-3b85-4301-a63d-5be54dcf1966.png)
![right-2](https://user-images.githubusercontent.com/65308831/181365559-9dd5c852-669c-4e56-a564-089634350ef7.png)
![right-3](https://user-images.githubusercontent.com/65308831/181365581-00f57ae7-438c-4268-8130-c68e368f2370.png)
![right-4](https://user-images.githubusercontent.com/65308831/181365595-5f7ce592-2466-4f10-b7ab-a87f6f8aa559.png)
![right-5](https://user-images.githubusercontent.com/65308831/181365609-96fc9cc2-11c5-481c-bfb1-9ac749a00b3f.png)
![right-6](https://user-images.githubusercontent.com/65308831/181365619-d1833e21-861b-4995-bac5-381175de33be.png)
![right-7](https://user-images.githubusercontent.com/65308831/181365640-28323dfe-a14e-458e-88b7-032dade50b68.png)

## ROS launch file
![launch](https://user-images.githubusercontent.com/65308831/181365657-85e9e76c-07aa-4710-8ced-d0f4d996a7e4.png)

## ROS config for the left camera
![config-left](https://user-images.githubusercontent.com/65308831/181365692-6a572946-07b4-4303-bdb5-a2cf66d110cb.png)

## ROS config for the right camera
![config-right](https://user-images.githubusercontent.com/65308831/181365696-54197f3a-7a0f-49ba-914a-d198cfc392ee.png)

## Error message and information related to image topics
![exe1](https://user-images.githubusercontent.com/65308831/181365754-357fa8cd-f6b7-4a40-827a-566e65d4f0c2.png)
![exe2](https://user-images.githubusercontent.com/65308831/181365759-9a4931e3-f7e3-4aa4-82c7-9947ca8a9cf0.png)

Thank you for your time,

**Comment by farhad-dalirani** [comment]
If you need more detail let me know.

**Comment by FrancoisPicardDTI** [comment]
Hello @farhad-dalirani 
Difficult to see what is wrong here. For the sake of testing here, can you comment in your ROS config files the parameters related to the brightness (brightness and brightness_continuous)? What is happening when you try then to start your process?

**Comment by FrancoisPicardDTI** [comment]
I am closing this issue for now as it does not seem to be active anymore.

**Comment by rows-of-houses** [comment]
It seems like I managed to synchronize two Basler USB 3.0 cameras with a hardware trigger in ROS Noetic. I have two daA1280-54uc cameras.
I didn't change configuration of the cameras in Pylon viewer. I don't use any user presets. I provide all parameters either as ROS parameters or calling ROS services in launch file, like in mine (I can't paste it all for unknown reasons, so I provide screenshot)

`<?xml version="1.0"?>
<launch>
	<group ns="camera">
		<arg name="respawn" default="false" />
		<arg name="debug" default="false" />
		<arg name="mtu_size" default="1500" />
		<arg name="startup_user_set" default="CurrentSetting" />
		<arg name="enable_status_publisher" default="true" />
		<arg name="enable_current_params_publisher" default="true" />
		<arg name="config_file" default="$(find pylon_camera)/config/default.yaml" />
		<arg name="frame_rate" default="20"/>
		<arg name="binning_x" default="2"/>
		<arg name="binning_y" default="2"/>
		<arg unless="$(arg debug)" name="launch_prefix" value="" />
		<arg     if="$(arg debug)" name="launch_prefix" value="gdb -ex run --args" />
		
		<node name="left" pkg="pylon_camera" type="pylon_camera_node" output="screen"
		      respawn="$(arg respawn)" launch-prefix="$(arg launch_prefix)">
		    
		    <param name="gige/mtu_size" value="$(arg mtu_size)"/>
		    <param name="device_user_id" value="left"/>
		    
		    <param name="enable_status_publisher" value="$(arg enable_status_publisher)"/>
		    <param name="enable_current_params_publisher" value="$(arg enable_current_params_publisher)"/>
		    <param name="frame_rate" value="$(arg frame_rate)"/>
		    <param name="binning_x" value="$(arg binning_x)"/>
		    <param name="binning_y" value="$(arg binning_y)"/>
		    
		</node>

		<node name="right" pkg="pylon_camera" type="pylon_camera_node" output="screen"
		      respawn="$(arg respawn)" launch-prefix="$(arg launch_prefix)">
		    
		    <param name="device_user_id" value="right"/>
		    <param name="gige/mtu_size" value="$(arg mtu_size)"/>
		    
		    <param name="enable_status_publisher" value="$(arg enable_status_publisher)"/>
		    <param name="enable_current_params_publisher" value="$(arg enable_current_params_publisher)"/>
		    <param name="frame_rate" value="$(arg frame_rate)"/>
		    <param name="binning_x" value="$(arg binning_x)"/>
		    <param name="binning_y" value="$(arg binning_y)"/>
                    
		</node>
		<node pkg="rosservice" type="rosservice" name="reverse_x" args="call /camera/right/set_reverse_x true"/>
		<node pkg="rosservice" type="rosservice" name="reverse_y" args="call /camera/right/set_reverse_y true"/>
		<node pkg="rosservice" type="rosservice" name="set_trigger_source" args="call /camera/right/set_trigger_source 1"/>
		<node pkg="rosservice" type="rosservice" name="set_line_selector_r" args="call /camera/right/set_line_selector 0"/>
		<node pkg="rosservice" type="rosservice" name="set_line_selector_l" args="call /camera/left/set_line_selector 0"/>
		<node pkg="rosservice" type="rosservice" name="set_line_mode_r" args="call /camera/right/set_line_mode 0"/>
		<node pkg="rosservice" type="rosservice" name="set_line_mode_l" args="call /camera/left/set_line_mode 1"/>
		<node pkg="rosservice" type="rosservice" name="set_line_source" args="call /camera/left/set_line_source 0"/>
		<node pkg="rosservice" type="rosservice" name="set_grabbing_strategy_l" args="call /camera/left/set_grabbing_strategy 1"/>
		<node pkg="rosservice" type="rosservice" name="set_grabbing_strategy_r" args="call /camera/right/set_grabbing_strategy 1"/>
				
		
	</group>
	
</launch>`
![Screenshot from 2023-05-05 10-49-28](https://user-images.githubusercontent.com/117982412/236403776-c527be75-0127-42d3-bb27-212d3ba47d19.png)

I checked two cameras with a timer on 60 Hz phone screen, it seems like they are synchronized with a accuracy of 0.016s.
![image](https://user-images.githubusercontent.com/117982412/236405169-308e90e7-29b6-4e05-b15b-f0204942e4b9.png)

I am setting up a stereo-inertial system for a robot navigation. I use Kalibr ROS package for calibration of the system. According to Kalibr, time offset between two frames is about 0.00015 s. That means that frames are really synchronized.

**Comment by ghost** [comment]
Hello @rows-of-houses ,

I am facing issues when I want to synchronize 2 acA1440-220uc basler cameras.
My setup is a few different compared to yours, as I am triggering my two cameras from the same signal coming from an arduino. The signal triggers on rising edge for both cameras, and I am using the ROS1 driver on ROS Noetic like you. I just set up the input port of the Arduino on Pylon viewer for both cameras.
The issue I am facing is that it is not synchronyzed at high frequencies, and I can see it by putting a timer as you did, and seeing different value on the timer from a same trigger. Also, I am wondering how did you use Kalibr ROS package to see the time offset.

If you have any clue...
