### ISSUE TITLE
Missing diagnostic_updater.hpp file while bulilding workspace

### ISSUE THREAD

**Issue by rows-of-houses** [basler/pylon-ros-camera#144]
I have an issue while building my workspace:

`Starting >>> pylon_ros2_camera_component
--- stderr: pylon_ros2_camera_component                             
In file included from /home/user/cam_ws/src/pylon_ros2_camera/pylon_ros2_camera_component/src/pylon_ros2_camera_node.cpp:31:
/home/user/cam_ws/src/pylon_ros2_camera/pylon_ros2_camera_component/include/pylon_ros2_camera_node.hpp:82:10: fatal error: diagnostic_updater/diagnostic_updater.hpp: No such file or directory
   82 | #include <diagnostic_updater/diagnostic_updater.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`
How can I deal with it?

**Comment by FrancoisPicardDTI** [comment]
Hi @rows-of-houses 
You're definitely right and I have recently updated the documentation. Sorry for that.
You have to install it manually.
If you're using galactic: sudo apt install ros-galactic-diagnostic-updater
On humble : sudo apt install ros-humble-diagnostic-updater
Does it solve your problem?

**Comment by FrancoisPicardDTI** [comment]
I am closing the issue. Please reopen it if it is not solved on your side.
