### ISSUE TITLE
Ability to specify remote camera IP address and bidirectional communication

### ISSUE THREAD

**Issue by bsteenput** [basler/pylon-ros-camera#149]
I'm using the ros2 basler camera package to interface with a remote camera that is not on the same network as my server. I would like to be able to specify the IP address of the remote camera and also specify the IP address of my server to the camera so that bidirectional communication can take place.

Currently, I have implemented a solution for this myself, but it is not well integrated into the package's codebase. It would be helpful if there were official options for specifying these IP addresses in the package.

Thank you for your consideration.

**Comment by FrancoisPicardDTI** [comment]
Hello @bsteenput 
If you have modified the pylon driver so that it solves your problem, please feel free to suggest a pull request, and I will have a lookk at it.
