### ISSUE TITLE
Setting auto_exposure_upper_limit has no effect

### ISSUE THREAD

**Issue by MrFresh1** [basler/pylon-ros-camera#15]
Config .yaml file needs the following line for auto_exposure_upper_limit to take an effect:

`startup_user_set: "Default"`

I suggest adding that to the default.yaml file or clarifying the use of auto_exposure_upper_limit in any other way.

**Comment by pablo-quilez** [comment]
Hello,

in order for use auto expose upper limit to have an effect, you need to activate Auto Expose through service /pylon_camera_node/set_exposure. In Default profile, it maybe by default activated.

Best,
Pablo
