### ISSUE TITLE
 use UserSet2 in rosrun image_view image_vi image:=/pylon_camera_node/image_raw  The video too slow

### ISSUE THREAD

**Issue by Nanmei** [basler/pylon-ros-camera#150]
this is pylon view setting:
![2023-03-14 10-30-15 的屏幕截图](https://user-images.githubusercontent.com/80303463/224885031-2d6096e5-d843-452e-b8b9-480df6f65cff.png)
![2023-03-14 10-30-43 的屏幕截图](https://user-images.githubusercontent.com/80303463/224885059-897b5115-6bdf-44b0-8d22-ff96aa8fabca.png)
![2023-03-14 10-31-25 的屏幕截图](https://user-images.githubusercontent.com/80303463/224885077-eecc9eb6-817a-4f4d-817a-b34ce75e4d6b.png)

![2023-03-14 10-31-45 的屏幕截图](https://user-images.githubusercontent.com/80303463/224889807-98e8e677-c492-4fb0-b2fc-b7e08e7efca4.png)
-b6d0-8

![2023-03-14 10-32-16 的屏幕截图](https://user-images.githubusercontent.com/80303463/224885095-e8368ed5-5436-486d-829e-e90d59e84b15.png)

this is the launch and yaml:
![2023-03-14 11-22-11 的屏幕截图](https://user-images.githubusercontent.com/80303463/224889968-e987cb64-7b6d-4abb-836f-68a3a514a89d.png)

first I save and load "UserSet2" in  pylon view,and in the launch I set startup_user_set : UserSet2, then roslacunch pylon_camera_node and rosrun image_view. When I move camera ,and 1 second later,image_view can show current picture,but in the pylon view, the video is so fast.

https://user-images.githubusercontent.com/80303463/224888951-9e4fa271-cab1-4f35-8d69-ff60fb578c11.mp4

when I chang UserSet2 to CurrentSetting, image_view can show the video is so fast like pylon view show. 

![2023-03-14 11-20-17 的屏幕截图](https://user-images.githubusercontent.com/80303463/224889983-a80222bc-53ce-4b75-adf8-6be69adc84d7.png)

https://user-images.githubusercontent.com/80303463/224889251-f9ac11c5-1a9c-480e-b6a0-713701296bf9.mp4

I  don't konw why , set UserSet2 can make image_view video too slow ,thanks, waiting for you reply.

**Comment by FrancoisPicardDTI** [comment]
Hello @Nanmei 
image_view is a ROS tool so maybe it is coming from there and not from the ROS driver. In your application, did you write a client retrieving the images from the driver and displaying them? If it is slow then the probem may come from the driver. Otherwise, it may be a ROS related one.

**Comment by Nanmei** [comment]
thanks for your reply,I add opencv code in pylon_camera_node.cpp. Opencv video show img_raw_msg_, but i watched the opencv video .it still slow .so I cant't know why   "  <arg name="startup_user_set" default="CurrentSetting" /> " set CurrentSetting  can work.  Set UserSet1 it work slow. I set frame_rate: 100, the video delay 1 second.  I think it is not  image_view problem. I need your help. thanks.
![2023-09-21 11-02-08 ](https://github.com/basler/pylon-ros-camera/assets/80303463/291d85a4-5b4c-4a4f-8a4c-0deb01161188)
![2023-09-21 11-45-09 ](https://github.com/basler/pylon-ros-camera/assets/80303463/95cb01e3-17b7-45bc-b456-11e0a87cd96c)
