### ISSUE TITLE
Convert blaze pointcloud to depth image

### ISSUE THREAD

**Issue by haopeng-qrt** [basler/pylon-ros-camera#153]
Hi, I'm using the humble version of blaze node to publish pointcloud. The pointcloud is subscribed from the message "/my_blaze/pylon_ros2_camera_node/blaze_cloud"

Then, I follow the workflow as below to convert it into a numpy array:
```console
import numpy as np
from sensor_msgs_py import point_cloud2

pointcloud = point_cloud2.read_points_numpy(data, field_names=("x", "y", "z"), skip_nans=False)
pointcloud_2D = np.reshape(pointcloud, (HEIGHT, WIDTH, 3))
depth_image = pointcloud_2D[:, :, 2]
```
where data is the received pointcloud message, HEIGHT, WIDTH is the resolution of the blaze camera (480x640)

However, the depth image I got looks like color splash noise, no image content can be visually identified. 

The same workflow works for the other depth camera such as intel realsense2 when converting pointcloud to depth image. Could you let me know where is the issue? Thanks!

**Comment by FrancoisPicardDTI** [comment]
Hello @haopeng-qrt 
In the pylon supplementary pack for blaze, there are a couple of examples in python that may solve your problem:
https://www.baslerweb.com/en/downloads/software-downloads/#type=baslerblazesoftware;language=all;version=all
This is not an issue related to the pylon driver itself so I am closing the issue. Please feel free to reach Basler support if you don't manage to solve your issue.
