### ISSUE TITLE
error: 'ChunkSelector_AutoBrightnessStatus' is not a member of 'Basler_UniversalCameraParam:ChunkSelectorEnums'

### ISSUE THREAD

**Issue by deuknyeonkim** [basler/pylon-ros-camera#154]
Hi, i am novice in Linux OS......
i have a problems while catkin_make procedures like below.....
![image](https://user-images.githubusercontent.com/128441477/227458043-47ae6708-4730-4874-bbfa-8d0e02e69a1e.png)

what can i do for fix the problems....

my pc version as like below.
Discription : Ubuntu 18.04.6 LTS
Codename : bionic
rosversion -d : Melodic

and hwinfo of camera is like below.
![image](https://user-images.githubusercontent.com/128441477/227457760-5dd7f8b4-0a2b-4f51-b232-b76729c5143f.png)

thank you and have a nice day~

**Comment by xiaowhite-22** [comment]
@deuknyeonkim  i also had the same problem, please how did you solve it.

**Comment by FrancoisPicardDTI** [comment]
Hello @deuknyeonkim and @xiaowhite-22 
I think you did not install the pylon SDK. I strongly suggest for you to look at the driver documentation and to look at all the tutorials ROS provide for. It is not an issue related to the driver itself, I am closing the issue.
