### ISSUE TITLE
[Noetic] error about rosdep install after pylon software installation.

### ISSUE THREAD

**Issue by mw-JHC** [basler/pylon-ros-camera#161]
Hi!

i am getting error to rosdep install after pylon software installation. 

i downloaded and installed pylon software version 6.2  from [here](https://www.baslerweb.com/en/downloads/software-downloads/software-pylon-6-2-0-linux-x86-64bit/)

and i command the below commands in my ubuntu to follow your readme.

```console
sudo sh -c 'echo "yaml https://raw.githubusercontent.com/basler/pylon-ros-camera/master/pylon_camera/rosdep/pylon_sdk.yaml" >   /etc/ros/rosdep/sources.list.d/30-pylon_camera.list' 
rosdep update
rosdep install --from-paths . --ignore-src --rosdistro=$ROS_DISTRO -y
```
but i get the error

```console
Found an existing Pylon installation in PYLON_ROOT but the version is too low
Found an existing Pylon installation in PYLON_ROOT but the version is too low
executing command [rosdep-source install https://raw.githubusercontent.com/magazino/pylon_camera/indigo-devel/rosdep/pylon_sdk.rdmanifest]
Found an existing Pylon installation in PYLON_ROOT but the version is too low
ERROR: installation failed:
source: installation script returned with error code
ERROR: the following rosdeps failed to install
  source: command [rosdep-source install https://raw.githubusercontent.com/magazino/pylon_camera/indigo-devel/rosdep/pylon_sdk.rdmanifest] failed
```

but in my docker its works very well...  

how can i fix it? pylon softeware installed without problem in /opt/pylon folder.

and other extra question is, if i want to use software version 5. xx , should i clone pylon-ros-camera from the branch pylon5-lagacy? 

my Ubuntu environment:
Ubuntu focal 20.04 x86_64
ROS noetic

my docker environment:
image: ros:noetic-ros-base-focal

thx for your help!

update:
![image](https://github.com/basler/pylon-ros-camera/assets/77030702/a24edf2e-e55c-4e5f-830d-c0c7a4b655c3)

even i installed pylon 7.3 still i have same problem.

**Comment by FrancoisPicardDTI** [comment]
Hello @mw-JHC 
The version of the pylon API you are working with is too old unfortunately. The ros driver is not maintained for older versions of pylon. But of course feel free to test the legacy pylon ros driver.
