### ISSUE TITLE
ros param device_user_id not working from .launch

### ISSUE THREAD

**Issue by TRA55A** [basler/pylon-ros-camera#172]
Hello,

I'm starting multiple Basler GigE cameras, and my aim is to initiate the pylon node using various camera IDs. However, it appears that when I set it from the launch file, it doesn't affect the driver. I wonder if I'm using it incorrectly?

Upon inspecting the code, I noticed the presence of nh.param<std::string>("device_user_id", device_user_id_, ""); but I couldn't find any corresponding call for nh.getParam("device_user_id", device_user_id_).

Best Regards.

**Comment by FrancoisPicardDTI** [comment]
Hello @TRA55A 
It is not possible to specify the device user id through the launch file. This id must be specified in the config/default.yaml file.
If you want to specify several .yaml files (you need one per camera in your case), you need to point to the right .yaml file when launching the node by specifying the "config_file" parameter. Let me know if it allows you to solve your issue.
