### ISSUE TITLE
Specific user set not loaded

### ISSUE THREAD

**Issue by fafux** [basler/pylon-ros-camera#174]
## Environment
* OS Version: Ubuntu 22.04 
* ROS2 version: humble

## Description
Through the pylonviewer I save some specific parameters as _UserSet3_. Then I launch the driver with the command: `ros2 launch pylon_ros2_camera_wrapper pylon_ros2_camera.launch.py --ros-args -p startup_user_set:=UserSet3`. Some of the parameters that I defined in the viewer (e.g. _exposure_ and some others) are loaded with the correct value, others (e.g. _image_encoding_, _frame_rate_, _gain_ and some others)  are loaded with the deafult ros value. I cannot understand why some should be loaded correctly with respect to the user defined options (_UserSet3_) and others not.

**Comment by FrancoisPicardDTI** [comment]
Hello @fafux
I am investigating. Can you give me the camera model you're using please?
Trying to reproduce the issue, I am noticing:
* The exposure is correctly modfied when loading the user set through the pylon driver.
* I don't see any problem with the gain either, except when I am modifying the image encoding, which modifies the min and max values of the gain. Can you describe a bit more what you are observing on your side please?
* Can you as well give me more info about the frame rate and the image encoding please?
Thanks a lot!
