### ISSUE TITLE
Add cameras using static IPs instead of name

### ISSUE THREAD

**Issue by mgeisslinger** [basler/pylon-ros-camera#175]
At the moment, the cameras are configured by assigning names.
However, this does not work anymore if the camera is assigned new static IPs, e.g., due to the usage of a VLAN.
Is there a known method to add the cameras by their IP and not their name?

**Comment by FrancoisPicardDTI** [comment]
Hello @mgeisslinger 
Not as of today, unfortunately. Maybe you can explain a bit more your use case and what you're trying to do?
Regards,
Francois
