### ISSUE TITLE
Compressed image in ROS2

### ISSUE THREAD

**Issue by Chiwingum11** [basler/pylon-ros-camera#182]
What should I do to be able to compress raw image using ros2 galactic? Can someone provide a step by step source to achieve this? Because data collected is too large and I would like to reduce it. Wasn't able to find a solution for ROS2 but there are many sources for ROS1

**Comment by FrancoisPicardDTI** [comment]
Hello @Chiwingum11 
This is not an issue related to the pylon driver. I suggest looking at the ROS2 related forums instead. Hopefully will you get more chances there.
regards,
Francois
