### ISSUE TITLE
Use the ROS2 parameter API instead of service calls

### ISSUE THREAD

**Issue by russkel** [basler/pylon-ros-camera#183]
Hello,

Just a feature suggestion: I think it would be great if the driver used the ROS2 parameter API instead of having a service call for every camera config variable.

Kind regards,

Russ

**Comment by FrancoisPicardDTI** [comment]
Hello @russkel 
Thanks for this suggestion. Do not hesitate to submit a PR if you implement this feature on your side.
Best regards,
Francois
