### ISSUE TITLE
Make Blaze camera dependency optional

### ISSUE THREAD

**Issue by tonynajjar** [basler/pylon-ros-camera#187]
Recently the prerequisite of installing [pylon Supplementary Package for blaze](https://www.baslerweb.com/de/support/downloads/downloads-software/) was added to the humble branch, breaking the build for anyone without this prerequisite. 
Can it somehow be made as an optional prerequisite to not break the build for those not using that camera? Thanks  

```
code/ros2_ws/src/pylon-ros-camera/pylon_ros2_camera_component/include/internal/impl/pylon_ros2_camera_blaze.hpp:36:10: fatal error: pylon/BlazeInstantCamera.h: No such file or directory
   36 | #include <pylon/BlazeInstantCamera.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by m-binev** [comment]
@FrancoisPicardDTI May you check that please. Making the prerequisite optional makes sense to me.

**Comment by FrancoisPicardDTI** [comment]
Hello @tonynajjar 

We have decided to include the blaze functionalities within the ROS2 branches, in order to ease the maintenance process of these branches. So you have to follow the new installation guidelines to build the pylon driver, and install the supplementary package for Blaze provided by Basler.

Regards,
Francois

**Comment by tonynajjar** [comment]
Alright that's your call however it would be nice to follow the best practice of not breaking the build on an old release and instead have the change lined up for the next release with some migration/release notes ([example](https://navigation.ros.org/migration/Iron.html)). Thank you

**Comment by FrancoisPicardDTI** [comment]
You're absolutely right. Thank you for this suggestion.

**Comment by FrancoisPicardDTI** [comment]
@tonynajjar do you recommend the use of tags through git?

**Comment by tonynajjar** [comment]
Well it depends what you want to achieve, tags are just a way to mark a static point in the git history. To release this package to the ROS buildfarm, I believe you will need to create tags, see https://docs.ros.org/en/iron/How-To-Guides/Releasing/Releasing-a-Package.html for more info
