### ISSUE TITLE
[Humble] build error: no member named OutlierRemovalTolerance

### ISSUE THREAD

**Issue by whoutman** [basler/pylon-ros-camera#189]
After following the updates as suggested in https://github.com/basler/pylon-ros-camera/issues/187, we still get a compilation error:

`ros_ws/src/pylon-ros-camera/pylon_ros2_camera_component/include/internal/impl/pylon_ros2_camera_blaze.hpp: In member function ‘virtual std::string pylon_ros2_camera::PylonROS2BlazeCamera::setOutlierRemovalTolerance(const int&)’:
/ros_ws/src/pylon-ros-camera/pylon_ros2_camera_component/include/internal/impl/pylon_ros2_camera_blaze.hpp:1054:21: error: ‘class Pylon::CBlazeInstantCamera’ has no member named ‘OutlierRemovalTolerance’; did you mean ‘OutlierRemovalThreshold’?
 1054 |         blaze_cam_->OutlierRemovalTolerance.SetValue(tolerance);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                     OutlierRemovalThreshold
`

As suggested by the compiler, should 'OutlierRemovalTolerance' be replaced by 'OutlierRemovalThreshold'?

**Comment by FrancoisPicardDTI** [comment]
Hello @whoutman 

Looks like you are using an outdated version of the pylon supplementary package.
The OutlierRemovalTolerance parameter was introduced with firmware version 4.6.2, the corresponding pylon Supplementary package is 1.3.1. Using a recent version of the pylon supplementary package should help to fix the compilation issues.
Best,
Francois
