### ISSUE TITLE
can't found pylon_camera pylon_camera_node

### ISSUE THREAD

**Issue by ne01230** [basler/pylon-ros-camera#192]
i have tried setting according to guidance Interfacing Basler Vision cameras with ROS, i have install pylon7.2.1 and the camera is a2A1920-51gmBAS,  is there anything wrong with those settings?
![error](https://github.com/basler/pylon-ros-camera/assets/32810438/5a2c6e2f-e46d-4133-b4f1-b35e1a5b2a83)

**Comment by jitaxis** [comment]
how was it solved?
