### ISSUE TITLE
Connection multiple cameras ROS2 and publish images

### ISSUE THREAD

**Issue by AshleyRoth** [basler/pylon-ros-camera#203]
Hello,

How can I connect two cameras and publish images from them to Rost topic?

Run two instances of the program?

Not stereo, just capturing images from two cameras and posting to a topic.

Thanks.

**Comment by AshleyRoth** [comment]
> Hello @AshleyRoth You need to start as many pylon camera nodes as you have cameras. See some answers here for instance: #152 #125

Hi, Thanks. I checked, it works

**Comment by saketc3112** [comment]
Hi @AshleyRoth,

I also want to connect multiple Basler cameras with ros2. It would be really helpful if you could share your modified script to add multiple camera nodes.

Thanks a lot!
