### ISSUE TITLE
ACE cameras PTP synchronization (acA_1920-40gc)

### ISSUE THREAD

**Issue by jordigc2** [basler/pylon-ros-camera#205]
Hello,

I have 2 ACE cameras that I would like to use with PTP clock synchronized to use them as stereo cameras over the ROS2 wrapper.
They are connected to a Jetson through a switch and everything is running in a docker container.

After specifying the set up I have, I will present the issue I am encountering that I am not able to find in any of the posted issues on the repo and neither in the Documentation.

The issue that I am facing is that there are some parameters that the only way that can be set are through the UserSet over the Pylon Viewer and then load the UserSet from the ROS Pylon wrapper. However, there are some parameters that get updated when loading the UserSet, such as the exposure, but others that are not getting updated, such as the Frame Rate or image_encoding. As you can see, I am setting the pixel format to Bayer RG 8, the Frame Rate is set to 20HZ with Sync Free Run Enabled and Exposure to 10000us over Pylon Viewer and stored in a User Set. In the loaded .yaml file the encoding, exposing and Frame Rate are commented out to check if the configuration of the User Set is being uploaded.

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/185e721e-b945-49bf-86c1-d12bf7939692)

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/210f8399-67b4-4f64-a910-5ea7fd9471df)

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/c5a15f8e-5ec6-4bdd-b2df-7765f2113819)

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/6d023190-343f-41af-bea6-f7291ffb9531)

When I start the ROS Pylon Wrapper I get the following output. You can see that exposure got updated as the value set in the Pylon Viewer, but neither the encoding and the frame rate got updated. They where set to what I think is a default value, mono8 and 5hz respectively. 

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/9b93e5e5-9dc2-43cc-a8ad-4ffbefc7fa24)

In the following image I am showing that the published HZ is even lower than 5hz. I have seen in other issues to set the "enable_current_params_publisher" to False and to use a free run by having the Trigger Mode OFF. Even this 2 modifications the published Hz are even lower than the set by Pylon which this do not correspond to the ones I am setting over the UserSet.

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/474e369d-59cd-4b60-9b8c-da4d1e85a1bc)

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/a798b0f4-542f-4e70-99a4-d110ccc3ef56)

If I check the result of such configuration when running the Pylon Viewer I can see that the image HZ are stable at 20FPS. This would be my goal to be able to synchronize the 2 ace cameras together.
![image](https://github.com/basler/pylon-ros-camera/assets/22197158/bb8de663-fb8d-46b2-ae11-681bc68a2c3f)

When going over the documentation, I have also seen the PTP services I thought that just by sending a `ros2 service call /my_camera/pylon_ros2_camera_node_camera1/enable_ptp std_srvs/srv/SetBool "{data: True}"`  and what I can see is the camera now running at exactly 5Hz but not as set in the UserSet.

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/1839a4fa-c45e-4f16-baa3-f34e4c8cc7a6)

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/fbcfa88d-c74d-48a6-98d3-483d698d2169)

After exposing my issues the questions I have are the following:
- Which are the parameters that I can update using Pylon Viewer?
- How can I verify that a parameter from pylon viewer is properly enabled? Such as the Sync Free Run parameter?
- In case the Sync Free Run and the PTP parameters are well set, how can I verify that the cameras are running at sync?
- Was it correct to call the PTP service to enable it? If yes, I will include it in the launch file after launching the pylon wrapper.

I hope all this information is enough to support me solve the issue I am facing with the ACE Cameras PTP synchronization.

Thank you in advance.

**Comment by jordigc2** [comment]
### UPDATES of further tests

From the previous message I sent until today I managed to synchronize the 2 cameras using the Pylon Viewer at 20Hz. However, the goal is to achieve such configuration using the Pylon ROS wrapper with the 2 cameras. 

I have been trying to have the same procedure that I managed to make work with the Pylon Viewer, but over the Pylon ROS2 Humble package that Basler provides.
What I am launching is what you can see in the attached file which basically launches the ROS2 node, then stops grabbing the 2 cameras, sets the PTP and Free run to True and then it starts grabbing frames again.
After this, I get all the good status ROS2 services responses meaning that it was all set successfully. When I check the FPS of each camera it seems to be stable at 20FPS as specified.

However, when I open rviz2 to visualize or record the ros2 topics into a rosbag I get the following error.

![image](https://github.com/basler/pylon-ros-camera/assets/22197158/341ee929-49b5-4cfb-be4b-c0aa40b5accc)

I have set the MTU of the ETH0 interface to have a MTU 9000, and when I check I can see it is set to 8966, which should be fine. And then I have also set the MTU size into the configuration of each camera and also the inter_pkg_delay of each camera to 100000.

I've also noticed that the traffic on the network interface is incoming 700 Mbit/s in the case of using Pylon Viewer, while a number between 400 and 500 while using the ROS driver. We are using the following 8 ports Switch https://www.downloads.netgear.com/files/GDC/GS108Tv3/GS108Tv3_GS110TPv3_DS.pdf 

Thus it makes me think that for some reason the driver is not correctly using the network capabilities. The setup between the ROS driver and Pylon viewer in terms of transport layer should be extremely similar.

Do you have any suggestions on the direction to go?

[launch.txt](https://github.com/basler/pylon-ros-camera/files/14833372/launch.txt)

**Comment by jordigc2** [comment]
### NEW UPDATE

By using the latest version of the Humble branch we realized that some parameters from the config file were not being applied. The issue was appearing because the Inter_pkg_delay parameter was not being updated and it was kept to a default value of 1000. By forcing the modification through the ros2 launch script it worked with no issues. 

Now we are able to have images at stable 20Hz using a 704Mb/s of bandwidth.

**Comment by nathan1536** [comment]
Hello @jordigc2  I'm student from Germany.

I do the setting similar to you. I try to synchronize two cameras using a PoE switch.
I follow your setting to achieve stable framerate of 20 HZ.
However, when I try to print timestamp from two camera node, 

ros2 topic hz /left/pylon_ros2_camera_node_left/image_raw
ros2 topic hz /right/pylon_ros2_camera_node_right/image_raw

The difference between the timestamps of two cameras is larger than I expected.
I guess it does not start to grab at same time.
Do you have any idea to synchronize them?

Thanks for your help.
