### ISSUE TITLE
No available camera. Keep waiting and trying...

### ISSUE THREAD

**Issue by zarathacia** [basler/pylon-ros-camera#206]
I tried it on the machine without docker the same problem occurs.

I am running the pylon ros camera package on a Noetic docker image. the installation was done successfully. The camera is connected using a USB connection. lsusb gives the camera id. but when running the pylon camera node is unable to find the camera. 

![image](https://github.com/basler/pylon-ros-camera/assets/38890049/d4c29f1a-37c6-4b77-bc55-a92f565bee8e)
I put the device user id in the default.yaml file like this: 

![image](https://github.com/basler/pylon-ros-camera/assets/38890049/7e29f8bb-35b6-4c56-b87b-580ff4fc0a7f)

**Comment by SMA2016a** [comment]
does lsusb see the camera?

**Comment by zarathacia** [comment]
hello, yes lsusb sees the camera. it turns out the installed driver is not compatible with the camera i possess. I needed to install the version 6.
Thank you for the response.
