### ISSUE TITLE
Merge PR168_change_setLineMode_behavior into Humble

### ISSUE THREAD

**Issue by alireza-moayyedi** [basler/pylon-ros-camera#215]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

Hello @FrancoisPicardDTI ,

As mentioned in https://github.com/basler/pylon-ros-camera/pull/168#issuecomment-2078949903 I have tested the PR168_change_setLineMode_behavior branch and it works fine. Could you please merge it into Humble?

### Hardware setup description

a2A4504-18umPRO

### Runtime information

```shell
Humble
```

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes

**Comment by FrancoisPicardDTI** [comment]
Hello @alireza-moayyedi 
It is now merged! Thank you for your contributions!
