### ISSUE TITLE
changes not reflected when launching camera with reverse_x and reverse_y set to true

### ISSUE THREAD

**Issue by dugtrio85** [basler/pylon-ros-camera#230]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

following the general usage of the launch file to start the camera, I understand that parameters can be set using the default.yaml file.

i tried adding `reverse_x: true` and `reverse_y: true` in the yaml config but my camera feed doesn't appear as it should be.

just FYI, my camera is mounted upside-down due to hardware design constraints. the feed is working fine, launching works too.

are the parameters name correct? or am i doing it wrongly?

### Hardware setup description

Running these services on a Nvidia Jetson Orin device, with cameras connected directly to the device.

### Runtime information

```shell
ROS2 Humble
Pylon Camera Software Suite 7.5.0
```

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes

**Comment by dugtrio85** [comment]
in `pylon_ros2_camera_component/include/pylon_ros2_camera_parameter.hpp`, i have declared
`

    bool reverse_x_;
    bool reverse_y_;
`

in `pylon_ros2_camera_component/src/pylon_ros2_camera_parameter.cpp`, i have added the reading from config
`

    RCLCPP_DEBUG(LOGGER, "---> reverse_x / reverse_y");
    if (!nh.has_parameter("reverse_x"))
    {
        nh.declare_parameter<bool>("reverse_x", false);
    }
    else 
    {
        nh.get_parameter("reverse_x", this->reverse_x_);
    }

    if (!nh.has_parameter("reverse_y"))
    {
        nh.declare_parameter<bool>("reverse_y", false);
    }
    else
    {
        nh.get_parameter("reverse_y", this->reverse_y_);
    }
`

in `pylon_ros2_camera_component/include/internal/impl/pylon_ros2_camera_gige.hpp` for example, i have added the lines to initialize the camera while taking in the parameters from the config file, depending on which device and profile type you are using you can add the code snippet in, for my example i was using the default profile in the gige camera type so i added it there
`

            cam_->ReverseX.SetValue(parameters.reverse_x_);
            cam_->ReverseY.SetValue(parameters.reverse_y_);

`

let me know what you guys think :)

**Comment by FrancoisPicardDTI** [comment]
Hello @dugtrio85 
That's one way to do it! Thank you for explaining your solution here.
Reverse_x and _y can be set through the available services implemented by the driver. That's the standard way to do it.
By doing the way you have implemented it, it works when you're starting the driver. But if you set the reverse parameters through the services afterwards, it won't update the parameters within the ros2 parameter server. That's why it is implemented like that for now.
It solved your problem, that's the most important :) Thank you again!
