### ISSUE TITLE
new: no such file or directory

### ISSUE THREAD

**Issue by clausMeko** [basler/pylon-ros-camera#235]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

Hi,

I need to _stream to a web endpoint_. Im fluent in golang so wanted to call c++ from golang.
I copied everything from `/opt/pylon/` to the exec dir

Can you assist me what the problem is?
```console
./Base/GCString.h:32:10: fatal error: new: No such file or directory
   32 | #include <new>
```
as far as i understood there should be a `new.h` somewhere? For the following includes in that file I would guess the same ist true.
  

### Hardware setup description

Specs:
* x86_64
* 32GB RAM
* Ubuntu 22.04
* usb3.0
* Basler ac1920-40uc

### Runtime information

```shell
(base) ➜  dev_ws echo $ROS_DISTRO
humble
```

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes

### Details

To reproduce I just call the generated API using:

```golang
package main

// #cgo LDFLAGS: -L. -lfancy
// #include "BaslerCameraSample.cpp"
import "C"

func main() {
	C.BaslerCameraSample()
}
```

I could zip and attach all the basler/pylon generated code.

**Comment by FrancoisPicardDTI** [comment]
Hello @clausMeko 
Sorry, this is not related to the ROS pylon driver.
I suggest you contact Basler support directly. I am closing the issue.
