### ISSUE TITLE
BUG: image_common should NOT be a submodule

### ISSUE THREAD

**Issue by ndahn** [basler/pylon-ros-camera#247]
### Issue description

*image_common* should be a  be a dependency in e.g. `pylon_ros2_camera_component/package.xml`, not a submodule. I'm not sure why this was ever approved, but it messes things up if people already have image_common in their workspace (e.g. a fork) as there are now multiple packages with the same name.

### Code example about how to reproduce the issue

1. Clone image_common into your workspace
2. Clone pylon-ros-camera into your workspace
3. Run `git submodule --init --recursive`
4. Try to build your workspace

### Error message

```shell
RuntimeError: Multiple packages found with the same name "camera_calibration_parsers":
- drivers/pylon_ros_camera/image_common/camera_calibration_parsers
- utils/image_common/camera_calibration_parsers
Multiple packages found with the same name "camera_info_manager":
- drivers/pylon_ros_camera/image_common/camera_info_manager
- utils/image_common/camera_info_manager
Multiple packages found with the same name "image_common":
- drivers/pylon_ros_camera/image_common/image_common
- utils/image_common/image_common
Multiple packages found with the same name "image_transport":
- drivers/pylon_ros_camera/image_common/image_transport
- utils/image_common/image_transport
```

### Hardware setup description

-

### Runtime information

```shell
-
```

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes

**Comment by FrancoisPicardDTI** [comment]
Hello @ndahn 
Look at the known issues section in the documentation.
I will try to remove it in the jazzy branch. Otherwise, it will stay as it is, except if some PR are submitted.
