### ISSUE TITLE
acA1920-40gc cameras chunk not supported error

### ISSUE THREAD

**Issue by jordigc2** [basler/pylon-ros-camera#249]
### Issue description

Hello,

I am using 2 acA1920-40gc  cameras which according to the [documentation](https://docs.baslerweb.com/data-chunks#trigger-input-counter-chunk) the Timestamp Chunk should be available.
![image](https://github.com/user-attachments/assets/2e959437-495c-48c0-a0b9-a88664ff4c50)

However, when I have the cameras running and sync with  PTP I could identify that with ROS there is a large latency which mess the full system where I require the timestamps to be precise.

Having a look into the issues, I could find these two,  #210 and #186, where they are mentioning the issue with similar cameras and marked as solved. However, when I follow the same steps as issue #186 I get the exact same issue.

```
root@ubuntu:~/cameras_ws# ros2 service call /my_camera/pylon_ros2_camera_node_camera2/stop_grabbing std_srvs/srv/Trigger
requester: making request: std_srvs.srv.Trigger_Request()

response:
std_srvs.srv.Trigger_Response(success=True, message='done')
---

root@ubuntu:~/cameras_ws# ros2 service call /my_camera/pylon_ros2_camera_node_camera2/set_chunk_mode_active std_srvs/srv/SetBool data:\ true
requester: making request: std_srvs.srv.SetBool_Request(data=True)

response:
std_srvs.srv.SetBool_Response(success=True, message='done')
---

root@ubuntu:~/cameras_ws# ros2 service call /my_camera/pylon_ros2_camera_node_camera2/set_chunk_selector pylon_ros2_camera_interfaces/srv/SetIntegerValue value:\ 29
requester: making request: pylon_ros2_camera_interfaces.srv.SetIntegerValue_Request(value=29)

response:
pylon_ros2_camera_interfaces.srv.SetIntegerValue_Response(success=True, message='done')
---

root@ubuntu:~/cameras_ws# ros2 service call /my_camera/pylon_ros2_camera_node_camera2/set_chunk_enable std_srvs/srv/SetBool data:\ true
requester: making request: std_srvs.srv.SetBool_Request(data=True)

response:
std_srvs.srv.SetBool_Response(success=True, message='done')
---

root@ubuntu:~/cameras_ws# ros2 service call /my_camera/pylon_ros2_camera_node_camera2/start_grabbing std_srvs/srv/Trigger
requester: making request: std_srvs.srv.Trigger_Request()

response:
std_srvs.srv.Trigger_Response(success=True, message='done')

root@ubuntu:~/cameras_ws# ros2 service call /my_camera/pylon_ros2_camera_node_camera1/get_chunk_timestamp pylon_ros2_camera_interfaces/srv/GetIntegerValue {}
requester: making request: pylon_ros2_camera_interfaces.srv.GetIntegerValue_Request()

response:
pylon_ros2_camera_interfaces.srv.GetIntegerValue_Response(value=-1, success=False, message='The connected camera does not supporting this feature')

```
Following the issue #186 I also tested it in Pylon Viewer if the chunk was working there. As you can see in the attached picture everything is enabled and running with no issues. And there when I check into the Chunk data I can see that the Chunk Timestamp is getting updated.

I did a last test where I am setting up all the chunk setting at the moment of the launch. Following the same principle as done with Pylon Viewer. You can see the starting script where I am setting everythin with the ROS2 services. [start.sh.txt](https://github.com/user-attachments/files/17559797/start.sh.txt)

However, after having all this settings and I visualize the 2 stamps in plotjuggler, where I would expect them to be perfectly aligned, I can see that there is a constant deviation between them as you can see in the attached image.

![stamp-no-sync-2](https://github.com/user-attachments/assets/6e61c510-9e5e-4315-9e35-f1b7a590fa2c)

Is there something that I am missing that is preventing the ROS2 node from grabbing the timestamp from the raw camera acquisition instead of the ROS node timestamp?

Thank you very much for your support.

Best regards,
Jordi

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes

**Comment by jordigc2** [comment]
It was an internal bug.

**Comment by jordigc2** [comment]
It was an internal bug.

**Comment by jordigc2** [comment]
solved. It was an internal bug. 

We were subscribing to the compressed images using image transforms and publishing to the same topic as the raw images. This was making that our raw images were not synchronized as expected.

**Comment by FrancoisPicardDTI** [comment]
Great. Thank you @jordigc2
