### ISSUE TITLE
Error for set_image_encoding service

### ISSUE THREAD

**Issue by duasob** [basler/pylon-ros-camera#256]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

I want to change the image_encoding, following [this issue](https://github.com/basler/pylon-ros-camera/issues/84). 

When I call the service:
```
ros2 service call /my_camera/pylon_ros2_camera_node/set_image_encoding pylon_ros2_camera_interfaces/srv/SetStringValue {value: mono16}
```

I get error: 
``
usage: ros2 [-h] [--use-python-default-buffering] Call `ros2 <command> -h` for more detailed usage. ...
ros2: error: unrecognized arguments: mono16}
```

I tried different combinations of inverted commas, but none of them seem to work

### Hardware setup description

I am using ROS2 Humble, connected over USB 3.0, for basler acA2040-90uc

### Runtime information

```shell
/
```

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes

**Comment by FrancoisPicardDTI** [comment]
Hello @duasob 

Try `ros2 service call /my_camera/pylon_ros2_camera_node/set_image_encoding pylon_ros2_camera_interfaces/srv/SetStringValue "{value: mono16}"`

This is not a pylon driver problem, but related to ROS2 and how to use it. I suggest reading the ROS2 documentation and following the tutorials : https://docs.ros.org/en/humble/index.html
