### ISSUE TITLE
pylon/BlazeInstantCamera.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [basler/pylon-ros-camera#258]
### Issue description

pylon/BlazeInstantCamera.h: No such file or directory

### Code example about how to reproduce the issue

pylon/BlazeInstantCamera.h: No such file or directory

### Error message

```shell
pylon/BlazeInstantCamera.h: No such file or directory
```

### Hardware setup description

Ubuntu 2004 x86_64

### Runtime information

```shell
pylon/BlazeInstantCamera.h: No such file or directory
```

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes

**Comment by FrancoisPicardDTI** [comment]
Hello @haifenglv 
Did you install the pylon supplementary package for Blaze?
