### ISSUE TITLE
pylon_camera fps cannot exceed 75

### ISSUE THREAD

**Issue by arunavanag591** [basler/pylon-ros-camera#27]
Hello,
I am using pylon_camera for my Basler acA1300-200uc. However, as put the fps to be 100 or higher in the launch file, the rosout shows that it has launched the camera at that specific frame rate.
`[ INFO] [1583442203.551151871]: Start image grabbing if node connects to topic with a frame_rate of: 100 Hz`

However when I check the topic
`rostopic hz /pylon_camera_node/image_raw`

I only get 75fps.
`min: 0.012s max: 0.015s std dev: 0.00029s window: 70
`
Is there a way to get higher fps. I have already tried with the basler application, which works fine and gives me a higher frame rate, so it is not an issue with the hardware or the connectors.

I looked into: https://github.com/magazino/pylon_camera/issues/25 and related issue to it but it did not help.

**Comment by claudiofantacci** [comment]
May be related to #28 and/or #29.

**Comment by arunavanag591** [comment]
Is there a test branch or PR that has contains those changes in #28 and #29 ?

**Comment by claudiofantacci** [comment]
Hey @arunavanag591! Unfortunately I have no code available, but you can easily test it by just hardcoding fixed timeouts and by passing a non default first argument to the camera constructor.

**Comment by arunavanag591** [comment]
Does the enum `TriggerModeEnums` as worked around here:

https://github.com/basler/pylon-ros-camera/blob/9f3832127fc39a2c181cbeb5257054352e2ef7fe/pylon_camera/include/pylon_camera/internal/impl/pylon_camera_base.hpp#L461-L480

**Comment by claudiofantacci** [comment]
I didn’t change that specifically. Just reduced the timeout and no buffermode on camera

**Comment by arunavanag591** [comment]
I tried all the recommended values in the issues but they did not work ! I am capped at 75 fps. The values maybe specific to the model of the camera.
My model is : Basler acA1300-200uc

**Comment by claudiofantacci** [comment]
Yes, most probably. Just out of curiosity: are you losing/dropping a lot of frames?

**Comment by pablo-quilez** [comment]
Hello,

it may be related to software triggering. This software triggering may reduce the framerate to 50%. This topic is something which we will address together with the other similar open issues.

Thanks!

**Comment by arunavanag591** [comment]
@pablo-quilez is there a PR or issue I can follow ?

**Comment by pablo-quilez** [comment]
@arunavanag591 not yet, sorry, but I will keep you informed.

**Comment by pablo-quilez** [comment]
Hello @arunavanag591,

I hope the last update we did in devel branch will solve this issue. I keep the issue open for a while until someone else can verify the correct behavior. Thanks!

Cheers

**Comment by FrancoisPicardDTI** [comment]
Closing the issue here as it seems that the update from December 15th, 2020 solved the problem.
