### ISSUE TITLE
The Image is dark , it looks like the green values are surpassing r and g values

### ISSUE THREAD

**Issue by jediofgever** [basler/pylon-ros-camera#31]
what is wrong with this camera , when i receive the image it has a weird format the looks darkish. 
I changed format to rgb8 but still cant geta normal looking rgb image, has anyone had same problem ?

**Comment by jediofgever** [comment]
![cap](https://user-images.githubusercontent.com/18460336/78105808-98d59400-7424-11ea-8a0f-e4359619b671.png)

**Comment by pablo-quilez** [comment]
Hello,

unfortunately as you are the only person having this or similar issues, we need more debugging information to proceed. Please provide:
- your camera model
- rest of configuration: gamma, brightness, etc.
- which format are you using for publishing the information

I suggest that you check directly with Pylon Viewer application to discard a hardware issue. https://www.baslerweb.com/en/products/software/basler-pylon-camera-software-suite/

Thanks!
