### ISSUE TITLE
rosdep install fails due to wrong checksum

### ISSUE THREAD

**Issue by stefanheyer** [basler/pylon-ros-camera#54]
executing command [rosdep-source install https://raw.githubusercontent.com/basler/pylon-ros-camera/master/pylon_camera/rosdep/pylon_sdk.rdmanifest]
ERROR: installation failed:
source: md5sum check on https://raw.githubusercontent.com/basler/pylon-ros-camera/master/pylon_camera/rosdep/empty.tar failed.  Expected df41600634ca08cb5082877eb64220c9 got d41d8cd98f00b204e9800998ecf8427e 
ERROR: the following rosdeps failed to install
  source: command [rosdep-source install https://raw.githubusercontent.com/basler/pylon-ros-camera/master/pylon_camera/rosdep/pylon_sdk.rdmanifest] failed

**Comment by pablo-quilez** [comment]
Hi, 

I cannot reproduce it. I have just downloaded the file and checked the md5. It is correct in my case:

```
curl -sL https://raw.githubusercontent.com/basler/pylon-ros-camera/master/pylon_camera/rosdep/empty.tar | md5sum | cut -d ' ' -f 1
df41600634ca08cb5082877eb64220c9
```

It may be related to an error in your connection.

Cheers.
