### ISSUE TITLE
How to zoom the picture when publishing it, instead of setting the roi of the picture.

### ISSUE THREAD

**Issue by panmengjia** [basler/pylon-ros-camera#79]
I just came into contact with the basler camera and don't know how to call the pylon API, and I am not too familiar with ros.
I want to set the output picture of basler camera to 752x480 size, I don’t know what to do.

**Comment by pablo-quilez** [comment]
Hello, currently the driver doesn't support changing the camera resolution. You will need to do it through the Pylon Viewer application from Basler: https://docs.baslerweb.com/overview-of-the-pylon-viewer.
Cheers
