### ISSUE TITLE
rosdep update error: <urlopen error [Errno 111]>

### ISSUE THREAD

**Issue by Deephome** [basler/pylon-ros-camera#80]
When I run: 
### sudo sh -c 'echo "yaml https://raw.githubusercontent.com/basler/pylon-ros-camera/master/pylon_camera/rosdep/pylon_sdk.yaml" > /etc/ros/rosdep/sources.list.d/30-pylon_camera.list' && rosdep update && sudo rosdep install --from-paths . --ignore-src --rosdistro=$ROS_DISTRO -y

Erros like this arised:

ERROR: unable to process source [https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml]:
	<urlopen error [Errno 111] Connection refused> (https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml)

How to fix it? thank you!

**Comment by saif-abdullah** [comment]
Hallo @Deephome ,
This issue has nothing to do with the Pylon driver.
You can't communicate with the ROS source server. This cause can be your internet firewall  or the DNS configuration.
