### ISSUE TITLE
continuous brightness / exposure control

### ISSUE THREAD

**Issue by RGring** [basler/pylon-ros-camera#82]
Hi,
My camera performs in changing lightning conditions. I would like configure continuous exposure control on a relatively low brightness level. I can configure successfully in the pylon viewer.

In ROS, I set the following parameters:

```
brightness: 80
brightness_continuous: true
exposure_auto: true
gain_auto: true
```

When starting the script it is not able to set a low brightness. Furthermore, it doesn't seem that the exposure is adjusted continuously. Here some output.

```
brightness is given and has value 80
brightness is continuous
exposure is set to auto
[ WARN] [1620723038.411178816]: Autoflash: 0, line2: 1 , line3: 1 
[ INFO] [1620723038.412110130]: No Device User ID set -> Will open the camera device found first
[ INFO] [1620723038.753256314]: Found camera with DeviceUserID : a2A1920-160ucBAS
[ WARN] [1620723039.054999243]: No User Set Is selected, Camera current setting will be used
[ INFO] [1620723039.058951591]: Cam supports the following [GenAPI|ROS] image encodings: ['Mono8'|'mono8'] ['Mono12'|'mono16'] ['Mono12p'|'NO_ROS_EQUIVALENT'] ['RGB8'|'rgb8'] ['BGR8'|'bgr8'] ['YCbCr422_8'|'NO_ROS_EQUIVALENT'] ['BayerRG8'|'bayer_rggb8'] ['BayerRG12'|'bayer_rggb16'] ['BayerRG12p'|'NO_ROS_EQUIVALENT'] 
[ WARN] [1620723039.155318843]: [] name not valid for camera_info_manager
[ INFO] [1620723039.183718111]: CameraInfoURL needed for rectification! ROS-Param: '/pylon/camera_info_url' = '' is invalid!
[ WARN] [1620723039.183831428]: Will only provide distorted /image_raw images!
[ WARN] [1620723049.792962822]: Did not reach the target brightness before timeout of 5 sec! Stuck at brightness 164.633 and exposure 13538us
[ INFO] [1620723049.793091701]: Setting brightness to: 80, reached: 164
[ INFO] [1620723049.796956283]: Startup settings: encoding = 'rgb8', binning = [1, 1], exposure = 13538, gain = 0, gamma = 1, shutter mode = global
[ INFO] [1620723049.797179740]: Start image grabbing if node connects to topic with a frame_rate of: 10 Hz
[ INFO] [1620723049.797284504]: Camera not calibrated
```
When I set the exposure manually, I can easily achieve a brightness of 80.
Any suggestions what is missing?
Thanks!

**Comment by m-binev** [comment]
@RGring Hi, I'd recommend to configure everything in pylon Viewer, save it into an User Set, e.g., User Set 1, make it the Default Startup Set (check: https://docs.baslerweb.com/user-sets) and don't do any similar configurations in ROS. Regards

**Comment by pablogago11** [comment]
Hi @m-binev ,

Sorry for re-opening this issue. We are working to integrate the camera in a vehicle with an easy GUI to control basic parameters such as `AutoFunctions` and `TargetBrightness`, hence we cannot setup a User Set and just upload it during startup. 

We have found that the ROS node only adjusts the `ExposureTime` although the `AutoGain` is set to true. We would like to reproduce the PylonViewer behaviour where you can explicitly set a `TargetBrightness` and adjust both `Gain` and `ExposureTime` according to a criteria such as `minimize gain`. 

Any idea or clue to include such functionalities in the ROS driver? We are developing with a ROS1 debian version and we have decided to include the `AutoGainContinuous` function from the sample code `ParametrizeCamera_Autofunctions` from the documentation inside the `pylon_camera_gige.hpp` (also the usb for successfully compiling). 

Any comment welcome, thanks!

**Comment by m-binev** [comment]
Hi @pablogago11 , thanks for the insights. 
I have a question: do you see/face any hurdles to implement the missing functions yourself? That is, the code is giving you all the freedom to do so.
FYI: if I would implement that for my purposes, I would go for ROS2 only, because ROS1 is actually "dead". Maybe you would like to consider that. 
Cheers
@FrancoisPicardDTI FYI
