### ISSUE TITLE
Rviz is not able to display Bayer images

### ISSUE THREAD

**Issue by ogamache** [basler/pylon-ros-camera#84]
Hello!

My image format is set to "bayer_rggb8". If I used rqt_image_view to display the image, I can see the image in color without problem.

Since Rviz is not able to display images encoded in Bayer (it shows gray images), do you have a conversion in your driver, or an option, to display the image correctly in Rviz?

(In the moment, Rviz is publishing the image in gray scale instead of in color.)

Thanks!

**Comment by pablo-quilez** [comment]
Hello,

depending on the camera model, different encoding formats are supported. They supported formats are displayed during driver loading in the console. If you want to change between formats, you can call the ros service /pylon_camera_node/set_image_encoding. I hope it helps!

Regards!
