### ISSUE TITLE
Too large image size ( 1.5 MB) 

### ISSUE THREAD

**Issue by siddharthayedida** [basler/pylon-ros-camera#87]
I have a usb camera whose compressed image size is more than 1.5 MB . In my application, I need to transmit the video to another remote pc using UDP. But unfortunately, udp is not allowing more than ( ~65kb) . 

Any way to do this ?

**Comment by pablo-quilez** [comment]
Sorry but this has nothing to do with this repository and the driver. Anyway, you need to divide the image in chunks and implement order data delivery.
