### ISSUE TITLE
 Basler Blaze performances and compatibility with ROS Melodic

### ISSUE THREAD

**Issue by mmahdi** [basler/pylon-ros-camera#90]
Hello,
I'm starting a projet with a basler blaze and I would like to know if it's compatible with ROS Melodic version. Also, any feedback on its outdoor performance and power consumption.
Thanks !

**Comment by m-binev** [comment]
@mmahdi Hi, this is the wrong project for Basler blaze, becuase this ROS adapter supports 2D cameras only. Instead, download the blaze SDK from the Basler website and within it you will find an own ROS adapter. Regards
