### ISSUE TITLE
Basler ace2 launch fails

### ISSUE THREAD

**Issue by TRA55A** [basler/pylon-ros-camera#91]
**Hi all, I tried to use the example pylon_camera_node.launch but it shuts down immediately after launch.
I get the following error:**

user@user:~/catkin_ws$ roslaunch pylon_camera pylon_camera_node.launch
... logging to /home/user/.ros/log/0e717dce-3246-11ec-ade7-7470fd9fc28e/roslaunch-user-20007.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/user/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://user:33077/

SUMMARY

PARAMETERS
 * /pylon_camera_node/camera_frame: pylon_camera
 * /pylon_camera_node/camera_info_url: 
 * /pylon_camera_node/device_user_id: 
 * /pylon_camera_node/enable_current_params_publisher: True
 * /pylon_camera_node/enable_status_publisher: True
 * /pylon_camera_node/frame_rate: 5.0
 * /pylon_camera_node/gige/mtu_size: 1500
 * /pylon_camera_node/startup_user_set: CurrentSetting
 * /rosdistro: melodic
 * /rosversion: 1.14.12

NODES
  /
    pylon_camera_node (pylon_camera/pylon_camera_node)

ROS_MASTER_URI=http://localhost:11311

process[pylon_camera_node-1]: started with pid [20022]
[ WARN] [1634804355.173732239]: Autoflash: 0, line2: 1 , line3: 1 
[ INFO] [1634804355.174223827]: No Device User ID set -> Will open the camera device found first
[ INFO] [1634804355.481515489]: Found camera with DeviceUserID : a2A1920-51gcPRO
[ WARN] [1634804355.790390802]: No User Set Is selected, Camera current setting will be used
[ INFO] [1634804355.824778368]: Cam supports the following [GenAPI|ROS] image encodings: ['Mono8'|'mono8'] ['Mono10'|'NO_ROS_EQUIVALENT'] ['Mono10p'|'NO_ROS_EQUIVALENT'] ['Mono12'|'mono16'] ['Mono12p'|'NO_ROS_EQUIVALENT'] ['RGB8'|'rgb8'] ['BGR8'|'bgr8'] ['YCbCr422_8'|'NO_ROS_EQUIVALENT'] ['BayerRG8'|'bayer_rggb8'] ['BayerRG10'|'NO_ROS_EQUIVALENT'] ['BayerRG10p'|'NO_ROS_EQUIVALENT'] ['BayerRG12'|'bayer_rggb16'] ['BayerRG12p'|'NO_ROS_EQUIVALENT'] 
[ WARN] [1634804355.824980449]: No image encoding provided. Will use 'mono8' or 'rgb8' as fallback!
[ WARN] [1634804355.951127878]: [] name not valid for camera_info_manager
[ INFO] [1634804355.977003858]: CameraInfoURL needed for rectification! ROS-Param: '/pylon_camera_node/camera_info_url' = '' is invalid!
[ WARN] [1634804355.977095627]: Will only provide distorted /image_raw images!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while accessing ExposureTimeAbs in PylonGigECamera
[pylon_camera_node-1] process has died [pid 20022, exit code -6, cmd /home/user/catkin_ws/devel/lib/pylon_camera/pylon_camera_node __name:=pylon_camera_node __log:=/home/user/.ros/log/0e717dce-3246-11ec-ade7-7470fd9fc28e/pylon_camera_node-1.log].
log file: /home/user/.ros/log/0e717dce-3246-11ec-ade7-7470fd9fc28e/pylon_camera_node-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**I managed to open the camera and view/stream on the pylon viewer(6.2).**

**Did I miss something during the installation/configuration/launch?
If you have any suggestions on how to debug this issue, please let me know.**

**Comment by m-binev** [comment]
@TRA55A Hi, have you made sure that you use the pylon6-dev branch with ace2? Only this one supports ace2 cameras:
https://github.com/basler/pylon-ros-camera/tree/pylon6-dev 

This is the probable issue:
what(): Error while accessing ExposureTimeAbs in PylonGigECamera
That is,  the ace 2 does not have ExposureTimeAbs parameter, but ExposureTime. This is surely one of the improvements in the pylon6-dev branch. Cheers
