### ISSUE TITLE
`rosdep [check|install] pylon_camera` fails if inaccessible folders exist in /opt

### ISSUE THREAD

**Issue by michael-sbarra** [basler/pylon-ros-camera#94]
`find: ‘/opt/XXX’: Permission denied`
Occurs when folders exist in /opt that the active user doesn't have read access to when running `rosdep [check|install] pylon_camera`

https://github.com/basler/pylon-ros-camera/blob/master/pylon_camera/rosdep/pylon_sdk.rdmanifest#L40-L41

`find` always returns a value of `1` when this happens even if pylon is installed (which should return `0`).

**Comment by michael-sbarra** [comment]
Resolved by #95

**Comment by pablo-quilez** [comment]
Hi @michael-sbarra

I recommend to do the PR to pylon6-dev branch and use this as basis. This is the newest state. Are you using pylon6 or 5?

**Comment by FrancoisPicardDTI** [comment]
PR included into the master branch (whch is the old pylon6-dev). I am closing this issue,
