### ISSUE TITLE
`rosdep install pylon_camera` fails installing pylon

### ISSUE THREAD

**Issue by michael-sbarra** [basler/pylon-ros-camera#96]
`dpkg: error: requested operation requires superuser privilege`

https://github.com/basler/pylon-ros-camera/blob/master/pylon_camera/rosdep/pylon_sdk.rdmanifest#L34-L35

`dpkg` needs to be run with sudo. Same with `udevadm`.

**Comment by michael-sbarra** [comment]
Running `rosdep` as sudo as the README states prevents this issue and allows for this dep to be installed in a sudo-less container, but it is potentially harmful when installing all deps from all packages. Closing for now.

**Comment by peci1** [comment]
#155 provides a proper solution allowing both use-cases.
